// Vendors foliate-js into src/vendor/foliate-js at a pinned commit.
//
// foliate-js has no usable npm release: the `foliate-js` package on npm is
// published by a third party rather than the author, and upstream states there
// is no release yet and that the API may change at any time. So we check in a
// copy pinned to a specific commit, and re-sync deliberately via this script.
//
//   npm run vendor:foliate           re-download and write src/vendor/foliate-js
//   npm run vendor:foliate -- --check  verify the tree on disk matches, write nothing
//
// Do not hand-edit anything under src/vendor/foliate-js -- --check will fail.

import { createHash } from "crypto";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const REPO = "johnfactotum/foliate-js";
const SHA = "78914aef4466eb960965702401634c2cb348e9b1";

const DEST = fileURLToPath(new URL("../src/vendor/foliate-js/", import.meta.url));

// Exactly the modules reachable from view.js once the PDF branch is patched
// out. Keeping this list explicit (rather than copying the whole repo) means an
// upstream module we never audited can't arrive silently.
const FILES = [
  "LICENSE",
  "README.md",
  // static imports of view.js
  "view.js",
  "epubcfi.js",
  "overlayer.js",
  "progress.js",
  "text-walker.js",
  // renderers, loaded dynamically by view.js
  "paginator.js",
  "fixed-layout.js",
  // format parsers, loaded dynamically by view.js
  "epub.js",
  "mobi.js",
  "fb2.js",
  "comic-book.js",
  // other dynamic imports of view.js. tts.js is unused by this app, but the
  // dynamic import in initTTS() is a literal specifier and the bundler fails
  // the build on an unresolvable one -- copying is cheaper than a second patch.
  "search.js",
  "tts.js",
  "vendor/zip.js",
  "vendor/fflate.js",
];

// Deliberately excluded, asserted below so the exclusion stays intentional:
// pdf.js and vendor/pdfjs (PDFs render via react-pdf; vendor/pdfjs is ~10MB of
// pdfjs bundles and sourcemaps).
const EXCLUDED = ["pdf.js", "vendor/pdfjs"];

// PDFs are handled by react-pdf, so pdf.js and its vendored pdfjs build are not
// copied. Left alone, view.js would keep a dynamic import of a module that
// isn't there. Throwing here means makeBook() reports an unsupported type
// instead of the bundler failing on an unresolvable import.
const PDF_BRANCH_FROM = `    else if (await isPDF(file)) {
        const { makePDF } = await import('./pdf.js')
        book = await makePDF(file)
    }`;

const PDF_BRANCH_TO = `    // PATCHED by scripts/vendor-foliate.js: PDFs are rendered by react-pdf
    // (src/components/PdfViewer.tsx), so pdf.js and vendor/pdfjs are not
    // vendored. Throw rather than leave an unresolvable dynamic import.
    else if (await isPDF(file)) {
        throw new UnsupportedTypeError('PDF is not supported by this viewer')
    }`;

const PATCHES = {
  "view.js": [{ from: PDF_BRANCH_FROM, to: PDF_BRANCH_TO }],
};

/** The sha git would give this content, so we pin bytes and not just a ref. */
const gitBlobSha = (bytes) =>
  createHash("sha1")
    .update(`blob ${bytes.length}\0`)
    .update(bytes)
    .digest("hex");

const fetchOk = async (url, init) => {
  const response = await fetch(url, init);
  if (!response.ok) {
    throw new Error(`${response.status} ${response.statusText} for ${url}`);
  }
  return response;
};

const getTree = async () => {
  const response = await fetchOk(
    `https://api.github.com/repos/${REPO}/git/trees/${SHA}?recursive=1`,
    { headers: { Accept: "application/vnd.github+json" } }
  );
  const { tree, truncated } = await response.json();
  if (truncated) throw new Error("GitHub returned a truncated tree");
  return new Map(tree.map((entry) => [entry.path, entry]));
};

const download = async (file) => {
  const response = await fetchOk(
    `https://raw.githubusercontent.com/${REPO}/${SHA}/${file}`
  );
  return Buffer.from(await response.arrayBuffer());
};

const applyPatches = (file, bytes) => {
  const patches = PATCHES[file];
  if (!patches) return bytes;

  let text = bytes.toString("utf8");
  for (const { from, to } of patches) {
    if (!text.includes(from)) {
      throw new Error(
        `Patch target not found in ${file}. Upstream changed -- re-read the ` +
          `source at ${SHA} and update PATCHES in scripts/vendor-foliate.js.`
      );
    }
    text = text.replace(from, to);
  }
  return Buffer.from(text, "utf8");
};

const vendorManifest = (blobShas) =>
  JSON.stringify(
    {
      repo: `https://github.com/${REPO}`,
      sha: SHA,
      generatedBy: "scripts/vendor-foliate.js",
      patched: Object.keys(PATCHES),
      excluded: EXCLUDED,
      files: blobShas,
    },
    null,
    2
  ) + "\n";

const vendorReadme = () => `# Vendored foliate-js

Generated by \`scripts/vendor-foliate.js\`. **Do not edit these files by hand** --
run \`npm run vendor:foliate\` instead, and \`npm run vendor:foliate -- --check\`
to verify the tree still matches upstream.

- Source: https://github.com/${REPO}
- Pinned commit: \`${SHA}\`
- License: MIT (see \`LICENSE\`)

## Why vendored rather than an npm dependency

The \`foliate-js\` package on npm is published by a third party, not the author,
and upstream states there is no release yet and that the API may change at any
time. Pinning a commit and checking the tree in keeps the version we run
explicit and reviewable.

## Excluded from the copy

${EXCLUDED.map((x) => `- \`${x}\``).join("\n")}

PDFs are rendered by react-pdf (\`src/components/PdfViewer.tsx\`), so foliate's
experimental PDF adapter and its ~10MB vendored pdfjs build are not copied.

## Patches

\`view.js\` -- the PDF branch of \`makeBook()\` throws \`UnsupportedTypeError\`
instead of dynamically importing the excluded \`pdf.js\`.
`;

const collect = async () => {
  const tree = await getTree();

  for (const file of FILES) {
    if (!tree.has(file)) {
      throw new Error(`${file} is not in ${REPO}@${SHA} -- update FILES.`);
    }
  }
  for (const file of EXCLUDED) {
    if (!tree.has(file)) {
      throw new Error(
        `${file} is no longer in ${REPO}@${SHA}. It is on the exclusion list, ` +
          `so re-check whether the exclusion still means anything.`
      );
    }
    if (FILES.includes(file)) {
      throw new Error(`${file} is in both FILES and EXCLUDED.`);
    }
  }

  const blobShas = {};
  const contents = new Map();
  for (const file of FILES) {
    const bytes = await download(file);
    const sha = gitBlobSha(bytes);
    if (sha !== tree.get(file).sha) {
      throw new Error(
        `${file} content does not match the tree blob sha (got ${sha}, ` +
          `expected ${tree.get(file).sha}).`
      );
    }
    blobShas[file] = sha;
    contents.set(file, applyPatches(file, bytes));
  }
  return { blobShas, contents };
};

const write = async ({ blobShas, contents }) => {
  // Remove first so a file dropped upstream doesn't linger on disk.
  await fs.rm(DEST, { recursive: true, force: true });
  for (const [file, bytes] of contents) {
    const target = path.join(DEST, file);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, bytes);
  }
  await fs.writeFile(path.join(DEST, "VENDOR.md"), vendorReadme());
  await fs.writeFile(
    path.join(DEST, ".vendor-manifest.json"),
    vendorManifest(blobShas)
  );
  console.log(
    `Vendored ${contents.size} files from ${REPO}@${SHA.slice(0, 10)} into ` +
      path.relative(process.cwd(), DEST)
  );
};

const check = async ({ blobShas, contents }) => {
  const drift = [];
  for (const [file, bytes] of contents) {
    const target = path.join(DEST, file);
    const onDisk = await fs.readFile(target).catch(() => null);
    if (!onDisk) drift.push(`${file}: missing`);
    else if (!onDisk.equals(bytes)) drift.push(`${file}: differs`);
  }

  const manifestPath = path.join(DEST, ".vendor-manifest.json");
  const manifest = await fs.readFile(manifestPath, "utf8").catch(() => null);
  if (manifest !== vendorManifest(blobShas)) {
    drift.push(".vendor-manifest.json: differs");
  }

  if (drift.length) {
    console.error(
      `src/vendor/foliate-js does not match ${REPO}@${SHA.slice(0, 10)}:`
    );
    for (const line of drift) console.error(`  ${line}`);
    console.error("Run `npm run vendor:foliate` to regenerate.");
    process.exitCode = 1;
    return;
  }
  console.log(`src/vendor/foliate-js matches ${REPO}@${SHA.slice(0, 10)}`);
};

const collected = await collect();
if (process.argv.includes("--check")) await check(collected);
else await write(collected);
