/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlugininstallRouteImport } from './routes/plugininstall'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsPluginIdIndexRouteImport } from './routes/plugins/$pluginId.index'
import { Route as PluginsPluginIdOptionsRouteImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdFeedIndexRouteImport } from './routes/plugins/$pluginId/feed.index'
import { Route as PluginsPluginIdFeedSearchRouteImport } from './routes/plugins/$pluginId/feed.search'
import { Route as PluginsPluginIdFeedApiIdRouteImport } from './routes/plugins/$pluginId/feed.$apiId'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlugininstallRoute = PlugininstallRouteImport.update({
  id: '/plugininstall',
  path: '/plugininstall',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdIndexRoute = PluginsPluginIdIndexRouteImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsRouteImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdFeedIndexRoute =
  PluginsPluginIdFeedIndexRouteImport.update({
    id: '/plugins/$pluginId/feed/',
    path: '/plugins/$pluginId/feed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdFeedSearchRoute =
  PluginsPluginIdFeedSearchRouteImport.update({
    id: '/plugins/$pluginId/feed/search',
    path: '/plugins/$pluginId/feed/search',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdFeedApiIdRoute =
  PluginsPluginIdFeedApiIdRouteImport.update({
    id: '/plugins/$pluginId/feed/$apiId',
    path: '/plugins/$pluginId/feed/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/library': typeof LibraryRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/viewer': typeof ViewerRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/feed/$apiId': typeof PluginsPluginIdFeedApiIdRoute
  '/plugins/$pluginId/feed/search': typeof PluginsPluginIdFeedSearchRoute
  '/plugins/$pluginId/feed/': typeof PluginsPluginIdFeedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/library': typeof LibraryRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/viewer': typeof ViewerRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/feed/$apiId': typeof PluginsPluginIdFeedApiIdRoute
  '/plugins/$pluginId/feed/search': typeof PluginsPluginIdFeedSearchRoute
  '/plugins/$pluginId/feed': typeof PluginsPluginIdFeedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/library': typeof LibraryRoute
  '/plugininstall': typeof PlugininstallRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/viewer': typeof ViewerRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/feed/$apiId': typeof PluginsPluginIdFeedApiIdRoute
  '/plugins/$pluginId/feed/search': typeof PluginsPluginIdFeedSearchRoute
  '/plugins/$pluginId/feed/': typeof PluginsPluginIdFeedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate'
    | '/library'
    | '/plugininstall'
    | '/privacy'
    | '/settings'
    | '/viewer'
    | '/plugins/'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/feed/$apiId'
    | '/plugins/$pluginId/feed/search'
    | '/plugins/$pluginId/feed/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/library'
    | '/plugininstall'
    | '/privacy'
    | '/settings'
    | '/viewer'
    | '/plugins'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/feed/$apiId'
    | '/plugins/$pluginId/feed/search'
    | '/plugins/$pluginId/feed'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate'
    | '/library'
    | '/plugininstall'
    | '/privacy'
    | '/settings'
    | '/viewer'
    | '/plugins/'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/feed/$apiId'
    | '/plugins/$pluginId/feed/search'
    | '/plugins/$pluginId/feed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  LibraryRoute: typeof LibraryRoute
  PlugininstallRoute: typeof PlugininstallRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  ViewerRoute: typeof ViewerRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  PluginsPluginIdFeedApiIdRoute: typeof PluginsPluginIdFeedApiIdRoute
  PluginsPluginIdFeedSearchRoute: typeof PluginsPluginIdFeedSearchRoute
  PluginsPluginIdFeedIndexRoute: typeof PluginsPluginIdFeedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugininstall': {
      id: '/plugininstall'
      path: '/plugininstall'
      fullPath: '/plugininstall'
      preLoaderRoute: typeof PlugininstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId/'
      preLoaderRoute: typeof PluginsPluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/feed/': {
      id: '/plugins/$pluginId/feed/'
      path: '/plugins/$pluginId/feed'
      fullPath: '/plugins/$pluginId/feed/'
      preLoaderRoute: typeof PluginsPluginIdFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/feed/search': {
      id: '/plugins/$pluginId/feed/search'
      path: '/plugins/$pluginId/feed/search'
      fullPath: '/plugins/$pluginId/feed/search'
      preLoaderRoute: typeof PluginsPluginIdFeedSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/feed/$apiId': {
      id: '/plugins/$pluginId/feed/$apiId'
      path: '/plugins/$pluginId/feed/$apiId'
      fullPath: '/plugins/$pluginId/feed/$apiId'
      preLoaderRoute: typeof PluginsPluginIdFeedApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  LibraryRoute: LibraryRoute,
  PlugininstallRoute: PlugininstallRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  ViewerRoute: ViewerRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  PluginsPluginIdFeedApiIdRoute: PluginsPluginIdFeedApiIdRoute,
  PluginsPluginIdFeedSearchRoute: PluginsPluginIdFeedSearchRoute,
  PluginsPluginIdFeedIndexRoute: PluginsPluginIdFeedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
